name: kalkulator_bisnis_umkm
description: Aplikasi Kasir UMKM Sederhana
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  share_plus: ^10.1.4
  cupertino_icons: ^1.0.8

  # --- PLUGIN IKLAN APPODEAL ---
  # KITA KUNCI DI VERSI 3.0.0 (TIDAK BOLEH NAIK OTOMATIS)
  stack_appodeal_flutter: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Aset gambar tidak saya masukkan karena kamu pakai Icon bawaan di main.dart
