name: kalkulator_bisnis_umkm
description: Aplikasi Kasir UMKM Sederhana
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- PLUGIN WAJIB KASIR ---
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  share_plus: ^10.0.0
  cupertino_icons: ^1.0.2

  # --- PLUGIN IKLAN APPODEAL ---
  # SDK for Appodeal Ads monetization
  stack_appodeal_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Aset gambar tidak saya masukkan karena kamu pakai Icon bawaan di main.dart
